server:
  port: 51701

spring:
  application:
    name: leadnews-schedule
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/leadnews_schedule?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
  redis:
    host: localhost
    port: 6379

# 设置Mapper接口所对应的XML文件位置，如果你在Mapper接口中有自定义方法，需要进行该配置
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  # 设置别名包扫描路径，通过该属性可以给包中的类注册别名
  type-aliases-package: com.chenxu.model.schedule.pojos

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
#logging:
#  level:
#    org:
#     springframework: DEBUG
#     boot: DEBUG

